var pages = [
    'index.html',
    'contents.html',
    'history-table-layout.html',
    'history-table-layout-advantages.html',
    'history-table-layout-disadvantages.html',
    'positioning-title.html',
    'positioning-types.html',
    'positioning-absolute.html',
    'positioning-example-modal.html',
    'media-query-form.html',
    'flex-image-gallery.html',
    'grid-image-cards.html',
    'grid-scaling-hero.html',
    'grid-hanafuda.html',
];