var pages = [
    'index.html',
    'contents.html',
    'history-table-layout.html',
    'history-table-layout-advantages.html',
    'history-table-layout-disadvantages.html',
    'grid-basic-layout',
    'grid-image-cards.html',
    'grid-hanafuda.html',
    'resources-learning-more.html',
    'jen-simmons.html',
    'rachel-andrew.html',
    'chris-coyier.html',
    'layout-links.html',
];